name: Build AeroGamecenter

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Kodlari indir
        uses: actions/checkout@v4

      - name: Java kur
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Java dosyalarini derle
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path build
          $files = Get-ChildItem -Recurse -Filter *.java | Select-Object -ExpandProperty FullName
          javac -d build $files

      - name: JAR olustur
        shell: pwsh
        run: |
          jar --create --file AeroGamecenter.jar --main-class Main -C build .

      - name: EXE olustur
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist

          jpackage `
            --type exe `
            --name AeroGamecenter `
            --input . `
            --main-jar AeroGamecenter.jar `
            --main-class Main `
            --dest dist

      - name: EXE'yi artifact olarak yukle
        uses: actions/upload-artifact@v4
        with:
          name: AeroGamecenter-Windows
          path: dist/*.exe
